# Generated by Django 4.1.2 on 2022-10-12 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
