# Generated by Django 4.1.2 on 2022-10-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_approved_alter_album_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
