# Generated by Django 4.1.2 on 2022-10-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creation_time',
        ),
    ]
