# Generated by Django 4.1.2 on 2022-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0008_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
