# Generated by Django 4.1.2 on 2022-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0009_alter_song_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_time",
            field=models.DateTimeField(blank=True),
        ),
    ]
